[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["chmod +x railway_build.sh"]

[phases.build]
cmds = ["./railway_build.sh"]

[start]
cmd = "cd apps/api && node dist/main.js"
